const TRANSACTION_STATUS_TYPES = {
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  PENDING: "PENDING",
};

const TRANSACTION_NAMES = {};

const CHAIN_TYPES = {
  ETHEREUM_MAINNET: "eth",
  BSC_MAINNET: "bsc",
  KOVAN_TESTNET: "kovan",
  GANACHE_TESTNET: "ganache",
};

export { TRANSACTION_STATUS_TYPES, TRANSACTION_NAMES, CHAIN_TYPES };
